# This workflow will build a Java project with Gradle and publish to GitHub Actions maven repo
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Prepare to publish
      run: |
        echo '${{secrets.GPG_SECRET_KEY_CONTENT}}' | base64 -d > publish_key.gpg
        listOfSubProjectDirectories=( $( ls -d */) )
        for i in "${listOfSubProjectDirectories[@]}"
        do
           gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRET_PASSPHRASE}}" --output ${i}secret.gpg publish_key.gpg
        done
    - name: Publish to GitHub Packages
      run: ./gradlew publishGprPublicationToGitHubPackagesRepository -Pgpr.user=valentyn-namisnyk -Pgpr.key=${{ secrets.GITHUB_TOKEN }} -Psigning.secretKeyRingFile=secret.gpg -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}}
